version: '3.7'
services:
  web:
    build: ./pg
    restart: always
    command: flask run
    volumes:
      - ./pg:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
         - db
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jing
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=flask
    ports:
      - "5432:5432"
    expose:
      - 5432
      
  serving:
    build: ./tf_serving
    container_name: tf
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - 8080

volumes:
  postgres_data:
