"""empty message

Revision ID: 8a474e842272
Revises: 7d51a57b0985
Create Date: 2020-05-08 16:16:01.976663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a474e842272'
down_revision = '7d51a57b0985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('processed_filename', sa.String(), nullable=True))
    op.add_column('photo', sa.Column('processed_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'processed_url')
    op.drop_column('photo', 'processed_filename')
    # ### end Alembic commands ###
