"""empty message

Revision ID: 7d51a57b0985
Revises: a8182ebe0033
Create Date: 2020-05-07 23:45:52.775906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d51a57b0985'
down_revision = 'a8182ebe0033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('boxes', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('photo', sa.Column('classes', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('photo', sa.Column('num_detection', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('score', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'score')
    op.drop_column('photo', 'num_detection')
    op.drop_column('photo', 'classes')
    op.drop_column('photo', 'boxes')
    # ### end Alembic commands ###
