"""empty message

Revision ID: a8182ebe0033
Revises: 8f1c46eb507c
Create Date: 2020-05-06 21:07:45.536559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8182ebe0033'
down_revision = '8f1c46eb507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dev_users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dev_users', 'authenticated')
    # ### end Alembic commands ###
